name: jf_seehausen_kyffhaeuser
description: Jugendfeuerwehr Seehausen/Kyffhäuser App
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1
  intl: ^0.20.2
  firebase_core: ^3.15.0
  firebase_messaging: ^15.2.8
  flutter_local_notifications: ^19.3.0
  file_picker: ^10.2.0
  path: ^1.9.1
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/branding/logo.png
    - assets/branding/header_logo.png
    - assets/branding/splash_logo.png
    - assets/branding/app_icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/branding/app_icon.png
  adaptive_icon_background: "#0A1F44"
  adaptive_icon_foreground: assets/branding/app_icon.png

flutter_native_splash:
  color: "#0A1F44"
  image: assets/branding/splash_logo.png

  android_12:
    color: "#0A1F44"
    image: assets/branding/splash_logo.png
